# Site identity
title: dotlineform
url: "https://www.dotlineform.com"
baseurl: ""  # custom domain: leave empty
media_base: ""
media_prefix: /assets/works/img
files_prefix: /assets/works/files
# when using a separate media server, uncomment and set the following:
# media_base: https://media.dotlineform.com
# media_prefix: /works/img
# files_prefix: /assets/works/files

exclude:
  - scripts

collections:
  notes:
    output: true
    permalink: /notes/:name/  # clean note URLs
  poems:
    output: true
    permalink: /poems/:name/
  works:
    output: true
    permalink: /catalogue/works/:name/
  catalogue_notes:
    output: true
    permalink: /catalogue/notes/:name/

defaults:
  # Apply note layout automatically to the notes collection
  - scope:
      path: ""
      type: notes
    values:
      layout: note
  # Apply poem layout automatically to the poems collection
  - scope:
      path: ""
      type: poems
    values:
      layout: poem
  - scope:
      path: ""
      type: works
    values:
      layout: work
  - scope:
      path: ""
      type: catalogue_notes
    values:
      layout: catalogue_note    
  # Apply default layout automatically to other pages
  - scope:
      path: ""
    values:
      layout: default